server:
  port: 9000
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
    name: ribbon-consumer

management:
  server:
    port: 54001