server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://peer2:1112/eureka/
spring:
  application:
    name: hello-service
